[package]
name = "espn_wrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
thiserror = "2.0.3"
ureq = { version = "2.10.1", features = ["json"] }
